name: screenscraper
description: Emulation ROM scraper utilizing ScreenScraper API V2.
version: 0.0.2
repository: https://github.com/dsolonenko/screenscraper-api-dart

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  crypto: ^3.0.3
  json_annotation: ^4.8.1
  pretty_http_logger: ^1.0.1
  chunked_stream: ^1.4.2
  convert: ^3.1.1
  crclib: ^3.0.0
  collection: ^1.17.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
